# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Quernus
tagline:          'Matt Hamilton'
description:      'Matt Hamilton. An Internet technologist, interested in Python web development, iOS deployment and testing, wearables, networking and operating systems.'
url:              https://www.quernus.co.uk
baseurl:          /

author:
  name:           'Matt Hamilton'
  url:            https://twitter.com/hammertoe

paginate:         5

sass:
  style: compressed

collections:
  talks:
    output: true
